---
title: "A Content Analysis of Reddit User's Response Towards Students for Fair Admissions v. Harvard"
subtitle: "Term paper for SURV/SURVMETH 727"
author: "Chloe Chen & Kangrui Liu"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: TRUE
    df_print: kable
bibliography: references.bib
csl: american-sociological-association.csl
header-includes:
   - \usepackage{dcolumn} 

---

```{r setup, include=FALSE, tidy=TRUE}
knitr::opts_chunk$set(echo=TRUE,cache=TRUE, 
                      autodep=TRUE, cache.comments=FALSE,
                      message=FALSE, warning=FALSE,
                      fig.width=4.5, fig.height=3)
```

```{r, message = FALSE, warning = FALSE}
# load packages
library(xml2)
library(rvest)
library(tidyverse)
library(jsonlite)
library(robotstxt)
library(RSocrata)
library(dplyr)
library(tidytext)
library(tm)
library(RedditExtractoR)
library(stringr)
library(magrittr)
library(ggpubr)
library(zoo)
library(xts)
library(quanteda)
library(SentimentAnalysis)
library(vader)
library(GGally)
library(magrittr)
library(dplyr)
```

```{r, include = FALSE}
posts <- read.csv("../data/selected_posts.csv", 
                     header = TRUE, 
                     # sep = ";", 
                     encoding = "UTF-8") %>% distinct()
```


```{r, include = FALSE}
# load comments

comments <- read.csv("../data/scraped_comments_by_selected_posts.csv", 
                     header = TRUE, 
                     # sep = ";", 
                     encoding = "UTF-8") %>% distinct()

text_comments <- comments %>% dplyr::select(date,comment,url)

irrelevantWords <- c("[deleted]","[removed]")

filtered_comments <- text_comments %>% filter(comment != "[deleted]" & comment != "[removed]")
```

```{r, include = FALSE}
# load sm
sentiments <- read.csv("../data/sentiments.csv", 
                     header = TRUE, 
                     # sep = ";", 
                     encoding = "UTF-8")
```
## Introduction


## Data

### Reddit Data



### Twitter Data

## Results


### Data exploration

#### Clean up raw data



### Analysis

#### Get Sentiment Polarity


#### Sentiment Across Groups


## Discussion


## References

\linespread{1}


::: {#refs}

:::