```{r}
library(wordcloud)
library(tidytext)
library(tm)
library(RColorBrewer)
library(dplyr)
```

```{r}
# comments <- read.csv("data/scraped_comment.csv", 
#                      header = TRUE, 
#                      # sep = ";", 
#                      encoding = "UTF-8") %>% distinct()

comments <- read.csv("data/scraped_comments_by_selected_posts.csv", 
                     header = TRUE, 
                     # sep = ";", 
                     encoding = "UTF-8") %>% distinct()
```


```{r}
text_comments <- comments %>% dplyr::select(date,comment)
```


```{r}
irrelevantWords <- c("[deleted]","[removed]")

filtered_comments <- text_comments %>% filter(comment != "[deleted]" & comment != "[removed]")

```

```{r}
texts <- as_tibble(data.frame(filtered_comments$comment))

stop_words <- stopwords("en")

words <- texts %>%
  unnest_tokens(word, filtered_comments.comment)

words <- words %>%
  filter(!(word %in% stop_words))
```


```{r, warning=FALSE}
word_freq <- words %>%
  dplyr::count(word, sort = TRUE) %>%
  ungroup()
word_freq <- word_freq %>% filter(!grepl("^[A-Za-z]$", word))

wordcloud(words = word_freq$word, freq = word_freq$n, min.freq = 2,
          scale = c(4, 0.1), max.words = 1000, random.order = TRUE,
          rot.per = 0.5, colors = rainbow(6))
```

```{r}
# load sm
sentiments <- read.csv("data/sentiments.csv", 
                     header = TRUE, 
                     # sep = ";", 
                     encoding = "UTF-8")
```



```{r}
vaders_comments <- filtered_comments %>% dplyr::select(comment)

vaders_comments <- cbind(vaders_comments, sentiments$Vader)

colnames(vaders_comments) <- c("comment","vader")
```

```{r}
pos_comments <- vaders_comments %>% filter(vader > 0)

texts <- as_tibble(data.frame(pos_comments$comment))

stop_words <- stopwords("en")

words <- texts %>%
  unnest_tokens(word, pos_comments.comment)

words <- words %>%
  filter(!(word %in% stop_words))

word_freq_pos <- words %>%
  dplyr::count(word, sort = TRUE) %>%
  ungroup()

word_freq_pos <- word_freq_pos %>% filter(!grepl("^[A-Za-z]$", word))

wordcloud(words = word_freq_pos$word, freq = word_freq_pos$n, min.freq = 2,
          scale = c(4, 0.2), max.words = 400, random.order = TRUE,
          rot.per = 0.5,  colors = rainbow(6))
```

```{r}
neg_comments <- vaders_comments %>% filter(vader < 0)

texts <- as_tibble(data.frame(neg_comments$comment))

stop_words <- stopwords("en")

words <- texts %>%
  unnest_tokens(word, neg_comments.comment)

words <- words %>%
  filter(!(word %in% stop_words))

word_freq_neg <- words %>%
  dplyr::count(word, sort = TRUE) %>%
  ungroup()

word_freq_neg <- word_freq_neg %>% filter(!grepl("^[A-Za-z]$", word))

wordcloud(words = word_freq_neg$word, freq = word_freq_neg$n, min.freq = 2,
          scale = c(4, 0.2), max.words = 400, random.order = TRUE,
          rot.per = 0.5, colors = rainbow(6))
```
```{r}
neu_comments <- vaders_comments %>% filter(vader == 0)

texts <- as_tibble(data.frame(neu_comments$comment))

stop_words <- stopwords("en")

words <- texts %>%
  unnest_tokens(word, neu_comments.comment)

words <- words %>%
  filter(!(word %in% stop_words))

word_freq <- words %>%
  dplyr::count(word, sort = TRUE) %>%
  ungroup()
word_freq <- word_freq %>% filter(!grepl("^[A-Za-z]$", word))


wordcloud(words = word_freq$word, freq = word_freq$n, min.freq = 2,
          scale = c(4, 0.1), max.words = 400, random.order = FALSE,
          rot.per = 0.5, colors = rainbow(6))
```

```{r, warning=FALSE}
common_words_pos <- intersect(word_freq_pos[1:100,1],word_freq[1:100,1])

common_words_neg <- intersect(word_freq_neg[1:100,1],word_freq[1:100,1])

word_freq_pos <- word_freq_pos[!word_freq_pos$word %in% common_words_pos$word, ]

wordcloud(words = word_freq_pos$word, freq = word_freq_pos$n, min.freq = 2,
          scale = c(4, 0.1), max.words = 1000, random.order = TRUE,
          rot.per = 0.5,  colors = rainbow(6))

word_freq_neg <- word_freq_neg[!word_freq_neg$word %in% common_words_neg$word, ]

wordcloud(words = word_freq_neg$word, freq = word_freq_neg$n, min.freq = 2,
          scale = c(4, 0.1), max.words = 1000, random.order = TRUE,
          rot.per = 0.5, colors = rainbow(6))

```

